### ISSUE TITLE
<mat-select-country> inside  a Angular Material Table

### ISSUE THREAD

**Issue by CJiwan** [angular-material-extensions/select-country#123]
HI,
I try to shown the selected country in a Angular Material Table.
In the HTML template of my componant I put :
```
<ng-container matColumnDef="country">
        <th mat-header-cell *matHeaderCellDef>Pays</th>
        <td mat-cell *matCellDef="let element"><mat-select-country [value]="element.country"></mat-select-country></td>
      </ng-container>
```
In the ts I read a list of customer from a db.  With this list I create de datasource for the table : 
```
this.customerList.forEach((customer, index)=>{
           let newCountry: Country ={
            alpha2Code: customer.country, alpha3Code: "", callingCode: "", name: "", numericCode: ""

          };
          tempList.push({
            position: index+1,
            name: customer.name,
            country: newCountry,
            language: customer.language.name
          });
          this.lastIndex = index+1;
 });
this.customersTable = tempList;
```

In my database, the country is the alpha2Code. The result is ;
![image](https://user-images.githubusercontent.com/6518973/216812702-96ab09fb-e2be-4d89-a592-0ce803171c9f.png)

If I replace the [value]="element.country" by [value]="defaultValue" and defaultValue is : 
```
  defaultCountry: Country = {
    alpha2Code: "BE", alpha3Code: "", callingCode: "", name: "", numericCode: ""

  }
```

I obtain the correct result 
![image](https://user-images.githubusercontent.com/6518973/216813047-dfa63d24-1898-48b7-b8fa-0e895b6e51a4.png)

But of course it is not what a need to do.

 - OS:Windows 11
 - Browser : Edge
 - Version 109.0.1518.78 (Version officielle) (64 bits)

  Also tested with Chrome, the result is the same.

Thanks for your help

**Comment by Rogermax** [comment]
Hi, 

Not sure if it's going to work, but you should send to the component an object similar to the defaultCountry, one way to achieve that could be: 

```html
<ng-container matColumnDef="country">
    <th mat-header-cell *matHeaderCellDef>Pays</th>
    <td mat-cell *matCellDef="let element">
        <mat-select-country [value]="{alpha2Code: element.country}"></mat-select-country>
    </td>
</ng-container>
```

Or:

```html
<ng-container matColumnDef="country">
    <th mat-header-cell *matHeaderCellDef>Pays</th>
    <td mat-cell *matCellDef="let element">
        <mat-select-country [value]="{alpha2Code: element.country, alpha3Code: '', callingCode: '', name: '', numericCode: ''}"></mat-select-country>
    </td>
</ng-container>
```

Hope it helps you.

**Comment by CJiwan** [comment]
Hi,
Unfortunately I get the same result. And no errors are generated in console which could have helped.
Thanks 
Christian

**Comment by CJiwan** [comment]
Finaly that works.
I prepare the entry of the datasource with :
```
let newEntry = {
        position: index+1,
        name: customer.name,
        country:{
          alpha2Code: customer.country, alpha3Code: "", callingCode: "", name: "", numericCode: ""
        },
        language: customer.language.name
};
```
in the HTML : 
```
  <ng-container matColumnDef="country">
    <th mat-header-cell *matHeaderCellDef>Pays</th>
    <td mat-cell *matCellDef="let element"><mat-select-country [value]="element.country" [disabled]="true"></mat-select-country></td>
  </ng-container>
```

Thanks for your help
