### ISSUE TITLE
Importing HttpClientModule in this extension breaks the http interceptions

### ISSUE THREAD

**Issue by plamendp** [angular-material-extensions/select-country#13]
**Describe the bug**
Select Country module is importing HttpClientModule. If it is already imported earlier for any reason (great chance, because it is widely used), all interceptors created for the initially created HttpClient instance (during the first import) are ignored, simply because they are part of the previously injected HttpClient instance (https://angular.io/guide/http#setup-installing-the-module).

**To Reproduce**
1. Import HttpClientModule in app.module.ts
2. Create http interceptor and log something in console to see how it really works.
3. Create some other module and component which uses HttpClient (the instance, injected in some component).
4. Make a form using Country Select component and do an http request upon form submition. 
5. Interceptor will NOT log anything, because it is not triggered, because it is "hooked" to an HttpClient instance, not really injected in the "form" component. 

**Expected behavior**
HttpClientModule must be imported once.

**Comment by plamendp** [comment]
I'd suggest writing an instruction which modules it requires [to be imported], instead of blindly importing them in the extension.

**Comment by AnthonyNahas** [comment]
@plamendp thanks for opening this ticket! 

May you suggest a PR for that ?

**Comment by AnthonyNahas** [comment]
I've just removed `HttpClientModule` from the library


I will patch the package tonight


cheers 🍻

**Comment by AnthonyNahas** [comment]
[v1.3.0 is now live](https://www.npmjs.com/package/@angular-material-extensions/select-country)
