### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by mindarchitect** [angular-material-extensions/select-country#134]
**Describe the bug**
Angular 17 does not support the following modules which break component usage:

@angular/material/legacy-autocomplete
@angular/material/legacy-input

**To Reproduce**
1. Instal Angular 17
2. Create a component instance
3. Try to compile

**Expected behavior**
Angular 17 support

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 22.04.3
 - Chrome
 - Latest

**Additional context**
./node_modules/@angular-material-extensions/select-country/fesm2020/angular-material-extensions-select-country.mjs:5:0-85 - 

Error: 
Module not found: Error: Package path ./legacy-autocomplete is not exported from package [path]/node_modules/@angular/material (see exports field in [path]/node_modules/@angular/material/package.json)

Error: node_modules/@angular-material-extensions/select-country/lib/mat-select-country.component.d.ts:3:182 - error TS2307: Cannot find module '@angular/material/legacy-autocomplete' or its corresponding type declarations.

3 import { MatLegacyAutocomplete as MatAutocomplete, MatLegacyAutocompleteSelectedEvent as MatAutocompleteSelectedEvent, MatLegacyAutocompleteTrigger as MatAutocompleteTrigger } from "@angular/material/legacy-autocomplete";

Error: node_modules/@angular-material-extensions/select-country/lib/mat-select-country.component.d.ts:4:44 - error TS2307: Cannot find module '@angular/material/legacy-input' or its corresponding type declarations.

4 import { MatLegacyInput as MatInput } from "@angular/material/legacy-input";

**Comment by AnthonyNahas** [comment]
v17 has been just released
