### ISSUE TITLE
country phone prefixes in value object?

### ISSUE THREAD

**Issue by ArekSliwa** [angular-material-extensions/select-country#18]
**Describe the solution you'd like**
Would be nice to have country phone prefixes in value objects.

**Additional context**
It will extend usability of component.

**Comment by AnthonyNahas** [comment]
we should extend the db here `angular-material-extensions/select-county/projects/angular-material-extensions/select-country/src/lib/db.ts`

I would appreciate a PR

**Comment by essana3** [comment]
I suggest closing this, we already implemented it.

**Comment by balajibadly** [comment]
> I suggest closing this, we already implemented it.

can you show where it has been implemented?
