### ISSUE TITLE
No authorization token was found while importing MatSelectCountryModule

### ISSUE THREAD

**Issue by vandernath** [angular-material-extensions/select-country#19]
**Describe the bug**
When importing MatSelectCountryModule to an existing module.ts file, I'm getting No authorization token was found error.

**To Reproduce**
1. Using express-JWT to generate auth tokens.
2. import { MatSelectCountryModule } from '@angular-material-extensions/select-country';
3. Error happens.

**Expected behavior**
I'm not sure why the MatSelectCountryModule needs a auth, looking into it now.

**Comment by vandernath** [comment]
The problem appears to be related to https://github.com/angular-material-extensions/select-country/issues/13

**Comment by AnthonyNahas** [comment]
[v1.3.0 has been just release ](https://www.npmjs.com/package/@angular-material-extensions/select-country)
