### ISSUE TITLE
Predefined countries

### ISSUE THREAD

**Issue by petarplecas** [angular-material-extensions/select-country#20]
Is it possible to predefined countries somehow? Is there any solution available for now? If not is there any other way to do it?

**Comment by AnthonyNahas** [comment]
May you provide more information?

**Comment by petarplecas** [comment]
I work for a client who has a company that operates in 60 countries. I need a select-country field for those particular 60 countries. So is there a possibility to somehow say which countries I want? I do not need the whole list of countries.

**Comment by AnthonyNahas** [comment]
I understand! 

I will try to find a solution for the next minor update

**Comment by KingDarBoja** [comment]
Best idea would be setting [`countries`](https://github.com/angular-material-extensions/select-country/blob/master/projects/angular-material-extensions/select-country/src/lib/mat-select-country.component.ts#L53) property of `MatSelectCountryComponent` as an Input with default value `COUNTRIES_DB` (as it is right now).

**Comment by itsoisi** [comment]
#34 there is a pull request for the implementation. it also reduces the load time.

**Comment by AnthonyNahas** [comment]
I've just published a new minor version of the library that supports predefined countries.

[V2.1.0](https://www.npmjs.com/package/@angular-material-extensions/select-country)

Please refer to the below code as reference:

```html
<mat-select-country appearance="outline"
                    label="Country"
                    [countries]="predefinedCountries"
                    (onCountrySelected)="onCountrySelected($event)">
</mat-select-country>
```

```typescript
import {Country} from '@angular-material-extensions/select-country';

predefinedCountries: Country[] = [
    {
      name: 'Germany',
      alpha2Code: 'DE',
      alpha3Code: 'DEU',
      numericCode: '276'
    },
    {
      name: 'Greece',
      alpha2Code: 'GR',
      alpha3Code: 'GRC',
      numericCode: '300'
    },
    {
      name: 'France',
      alpha2Code: 'FR',
      alpha3Code: 'FRA',
      numericCode: '250'
    },
    {
      name: 'Belgium',
      alpha2Code: 'BE',
      alpha3Code: 'BEL',
      numericCode: '056'
    },
  ];
```


🥂
