### ISSUE TITLE
'disabled attribute with a reactive form directive' warning

### ISSUE THREAD

**Issue by fuegonju** [angular-material-extensions/select-country#21]
When debuging I get this message on the console using select-country extension:

 _It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors.
      Example:
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      });_

I'm using Angular 10.0.2 and I'm already using the 'disabled' option in my code without this warning.

**Comment by AnthonyNahas** [comment]
can you post your code?

html and ts ?

**Comment by AnthonyNahas** [comment]
this has been fixed with the latest release v3 (will be released soon)
