### ISSUE TITLE
Get an error when try to serve the project

### ISSUE THREAD

**Issue by AndriiPerun** [angular-material-extensions/select-country#22]
**Describe the bug**
When trying to serve the app I get an injection error. 

**To Reproduce**
1. Create a new angular app
2. Add **angular/cdk** and **angular/material** dependencies
3. Run "ng add @angular-material-extensions/select-country" 
4. Run "npm start'
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/37186921/87233115-44e82d00-c3cd-11ea-9dbf-44532365e0f2.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version  83.0.4103.116

**Additionally:**
 - dependencies:
![image](https://user-images.githubusercontent.com/37186921/87233211-29315680-c3ce-11ea-849b-36b34f24aca9.png)
- changes applied after run "ng add @angular-material-extensions/select-country":
    **angular.json**
![image](https://user-images.githubusercontent.com/37186921/87233227-4fef8d00-c3ce-11ea-8c65-b84861dd2c3d.png)

    **app.module.ts**
![image](https://user-images.githubusercontent.com/37186921/87233238-60076c80-c3ce-11ea-8c15-b8deb67c99c1.png)

Was anyone facing this issue?  What am I doing wrong?

**Comment by atgomes** [comment]
I am facing the same issue. Any ideas?

**Comment by ArekSliwa** [comment]
Yes I have the same. I downgrade for now to 1.2.0 and fixed to this version.

**Comment by jayaprakashmani92** [comment]
@ArekSliwa  After downgrade flag not showing. Any idea ?

**Comment by ArekSliwa** [comment]
hmm, strange. on my project I see flags on version 1.2.0. Could you check if you have svg elements inside dropdown items? and in Network that you have svgs

**Comment by AnthonyNahas** [comment]
This issue seems to appear since `v1.2.1`

the only change between `v1.2.0` to `v1.2.1` is that I updated angular material and some other packages....
<img width="408" alt="Bildschirmfoto 2020-07-17 um 20 35 10" src="https://user-images.githubusercontent.com/20149774/87819743-0f2fc200-c86d-11ea-8a0d-738afcea3ca9.png">

**Comment by AnthonyNahas** [comment]
Finally solved in [v.1.3.1](https://www.npmjs.com/package/@angular-material-extensions/select-country)


thanks for contributing 🍻
