### ISSUE TITLE
Error retrieving icons

### ISSUE THREAD

**Issue by Crazie-ash** [angular-material-extensions/select-country#23]
I followed these steps to install
![image](https://user-images.githubusercontent.com/45698249/87641003-24212e00-c765-11ea-9874-58fa507e0b16.png)

I got console issues as below
![image](https://user-images.githubusercontent.com/45698249/87641094-431fc000-c765-11ea-9945-14c9528fb408.png)

I am not sure why the flags svg folder were not loaded into assets. Please let me know where I am missing or is this a bug,

**Comment by ArekSliwa** [comment]
could you check this config in angular.json?:
`{
                "glob": "**/*",
                "input": "./node_modules/svg-country-flags/svg",
                "output": "/assets/svg-country-flags/svg"
              }`

**Comment by Tbiniimene** [comment]
same issue

**Comment by AnthonyNahas** [comment]
Can you show me please your imports ? and which lib version are you using ?

**Comment by JoseAlbertoVazq** [comment]
> could you check this config in angular.json?:
> `{
> 
> ```
>             "glob": "**/*",
> 
>             "input": "./node_modules/svg-country-flags/svg",
> 
>             "output": "/assets/svg-country-flags/svg"
> 
>           }`
> ```
> 
> I mean output, without src

This solution works for me but there is so many petitions, like, SO MANY, to retrieve the icons and page just freeze and the form has a huge lag until it finish... Furthermore I have 3 inputs in that form that needs this selector so the lag is three times longer. Any suggestion for that?

**Comment by Crazie-ash** [comment]
> could you check this config in angular.json?:
> `{
> 
> ```
>             "glob": "**/*",
> 
>             "input": "./node_modules/svg-country-flags/svg",
> 
>             "output": "/assets/svg-country-flags/svg"
> 
>           }`
> ```
> 
> I mean output, without src

This works great thanks 👍

**Comment by AnthonyNahas** [comment]
thanks for contributing 🥂

**Comment by KingDarBoja** [comment]
@AnthonyNahas Sorry for commenting on a old issue but this happened to me as well with latest version (2.0.0) and using the above output path does fix the issue. Should be good to update the readme to avoid this. Cheers!

**Comment by AnthonyNahas** [comment]
@KingDarBoja what should I update ? the path depends on your baseUrl .. 

that's why the snippet in the readme is still correct. ..

**Comment by KingDarBoja** [comment]
This is interesting as I didn't change the `baseUrl` made by Angular after creating the app. It is set to `"baseUrl": "./",` on my `tsconfig.base.json` file 🤔 and the [official docs](https://angular.io/guide/workspace-config#assets-configuration) seems to be the same as the readme.

Anyway, great library!

**Comment by wadie** [comment]
@AnthonyNahas I'm gonna have to comment on this one as well. Went through the same thing as @KingDarBoja 

Maybe mention in the docs that it depends on the baseUrl ? even though mine was simply `"./"`
