### ISSUE TITLE
Error: Can't resolve all parameters for MatSelectCountryModule: (?, ?)

### ISSUE THREAD

**Issue by hayha06** [angular-material-extensions/select-country#25]
When starting application I receive the following error 
Error: Can't resolve all parameters for MatSelectCountryModule: (?, ?)

My package.json 
`  "dependencies": {
    "@angular-material-extensions/select-country": "^1.3.0",
    "@angular/animations": "^9.1.12",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "^9.0.0",
    "@angular/compiler": "^9.0.0",
    "@angular/core": "^9.0.0",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "^9.1.12",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "^9.0.0",
    "@angular/platform-browser-dynamic": "^9.0.0",
    "@angular/platform-server": "^9.0.0",
    "@angular/router": "^9.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^7.1.1",
    "bootstrap": "^4.1.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^3.6.5",
    "hammerjs": "^2.0.8",
    "jquery": "^3.5.1",
    "popper.js": "^1.14.3",
    "rxjs": "^6.6.0",
    "rxjs-compat": "^6.4.0",
    "svg-country-flags": "^1.2.7",
    "zone.js": "^0.10.3"
  },`

**Comment by Tbiniimene** [comment]
+1

**Comment by JoseAlbertoVazq** [comment]
+1

**Comment by JoseAlbertoVazq** [comment]
I think that removing HttpClientModule from the library in the new 1.3.0 version in order to fix the interceptors issue made this issue. It would be great if this can be fixed soon because I am using http interceptors too in my project and now I can not event run the whole project.

**Comment by monikagujar** [comment]
![Screenshot from 2020-08-05 14-24-09](https://user-images.githubusercontent.com/25475597/89394252-784a7d00-d729-11ea-84e2-07f777ff7fd3.png)

I am also getting the same error

I just followed 2 steps:

1. Recommended installation
ng add @angular-material-extensions/select-country

2. added code in html
<mat-select-country>
</mat-select-country>

That's it

Referred this https://angular-material-extensions.github.io/select-country/doc/index.html

**Comment by Onelastfall** [comment]
In my project I am using Angular 8 and I was getting this error as well. I ended up by install version 1.2.0 and remove src from output:

              {
                "glob": "**/*",
                "input": "./node_modules/svg-country-flags/svg",
                "output": "/assets/svg-country-flags/svg"
              }

**Comment by AnthonyNahas** [comment]
Did you import the http client module ?

**Comment by Onelastfall** [comment]
> Did you import the http client module ?

This was imported in a sub-module without http module.

**Comment by AnthonyNahas** [comment]
Finally solved in [v.1.3.1](https://www.npmjs.com/package/@angular-material-extensions/select-country)


thanks for contributing 🍻

**Comment by wojciechhicu** [comment]
> In my project I am using Angular 8 and I was getting this error as well. I ended up by install version 1.2.0 and remove src from output:
> 
> ```
>           {
>             "glob": "**/*",
>             "input": "./node_modules/svg-country-flags/svg",
>             "output": "/assets/svg-country-flags/svg"
>           }
> ```

I did what you sayid and that worked for me thanks

**Comment by AnthonyNahas** [comment]
thanks for sharing 🐈
