### ISSUE TITLE
Serve error with esm5

### ISSUE THREAD

**Issue by itsoisi** [angular-material-extensions/select-country#27]
Hello,

i tried the latest version auf select-country v1.3.0. But starting the project with esm5 compiler doesn't work. Version 1.2.0 it works but there i have some issues with reactive forms (formGroups). It also doesn't work so i want the newest version.

The error is:

Compiling @angular-material-extensions/select-country : module as esm5
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected MatSelectCountryComponent to have an inner class declaration

tsconfig.json target => "target": "es5"

 - OS: Windows
 - Angular v 9.1.9

**Comment by AnthonyNahas** [comment]
duplicate to #22
