### ISSUE TITLE
Not nullable

### ISSUE THREAD

**Issue by josepaiva94** [angular-material-extensions/select-country#29]
Here we should have `} else if (this.nullable) {`, right?

https://github.com/angular-material-extensions/select-country/blob/8c490dd188697b5a964488cb8daea9165dd83b8c/projects/angular-material-extensions/select-country/src/lib/mat-select-country.component.ts#L108

**Comment by hrynko** [comment]
No, but there actually is an issue in the first part of the `if` statement. Thanks for noticing!
