### ISSUE TITLE
Missing country Mauritius

### ISSUE THREAD

**Issue by grantpullen** [angular-material-extensions/select-country#3]
The control currently does not include the country of Mauritius

**Comment by AnthonyNahas** [comment]
sorry but i dnt have any svg for Mauritius...

**Comment by grantpullen** [comment]
A svg flag can be found here: [https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg] It would be great if this control could support countries for which you don't currently have flags for, over-wise its use it limited. Much appreciated.

**Comment by AnthonyNahas** [comment]
I will add an option to add custom counties/flags

**Comment by grantpullen** [comment]
Much appreciated
