### ISSUE TITLE
Just flag is shown 

### ISSUE THREAD

**Issue by michelfigueiredojava** [angular-material-extensions/select-country#35]
If you show the component with:
`
            <mat-select-country appearance="standard"
                                label="Country"
                                formControlName="country"
                                [countries]="predefinedCountries">
            </mat-select-country>
`
and you have two countries:
`
        this.predefinedCountries = [
            {
                name: 'Brazil',
                alpha2Code: 'BR',
                alpha3Code: 'BRL',
                numericCode: '76'
            },
            {
                name: 'Greece',
                alpha2Code: 'GR',
                alpha3Code: 'GRC',
                numericCode: '300'
            },
`
when you set a selected country with:
`
        this.secondFormGroup = this.formBuilder.group({
            country: this.predefinedCountries[1]
        });
`
Then in the UI, you expect to see the text 'Greece' with its flag, but just the flag is shown:
![image](https://user-images.githubusercontent.com/45941874/91911133-5dc3df00-eca8-11ea-8795-b4a7e1a30b73.png)

**Comment by itsoisi** [comment]
I have the same issue. But it has nothing to do with the predefinedCountries. 
I tested both with and without predefined Countries.

There ist also a second issue withe reactive forms. When the control is disabled the country input is not disabled

![image](https://user-images.githubusercontent.com/48798711/91943304-a73e1980-ecfc-11ea-9498-25aead83b6ca.png)

```
      group[aform.objTag] = new FormControl(
        {value:this.resolve(aform.objTag,this.editData["data"]),disabled:this.editData['view'] || aform.disabled},
        validators
      );
```

**Comment by KingDarBoja** [comment]
Hello everyone, which version of the library are you using? Is it the latest one `2.2.0`?

**Comment by AnthonyNahas** [comment]
@KingDarBoja the latest version ist `2.2.0`

https://www.npmjs.com/package/@angular-material-extensions/select-country

@michelfigueiredojava which version are you using ?

**Comment by itsoisi** [comment]
i use the latest version 2.2.0

**Comment by michelfigueiredojava** [comment]
I believe I used the latest version too, the version 2.2.0.
Unfortunately I hat to gave up of this library and start using the ugly old select box.
I would be happy to fix this nice library and come up with a PR, but I am running out of time for that.

**Comment by AnthonyNahas** [comment]
I will try to fix that asap

I believe this happened since the merge of the latest PR which has few git conflicts...

**Comment by AnthonyNahas** [comment]
@michelfigueiredojava may you try please to downgrade the lib to either `1.3.1` or `1.0.1` ?? 

as quick solution for the moment

**Comment by SnappingTurtle** [comment]
Same problem here.   1.3.1 has same behaviour.  1.0.1 works fine.  Not sure what other surprises this older release might bring?
One other thing I noticed, that in the glitchy version, a click in the input control triggers the text value to be rendered.  So the value is set from initial property but it missed the change detection cycle on first render.

**Comment by AnthonyNahas** [comment]
this has been solved! 

new major release will be pushed soon

**Comment by dzena** [comment]
@AnthonyNahas 
Hi Anthony, do you need any support to make a release with latest changes (like the fix from this issue)? If there is anything I can support with, just drop a line and I hope I can find the time to support.
Thank you and keep up the good work.

**Comment by AnthonyNahas** [comment]
@KingDarBoja  you have right! Please when using the newest version `3.0.0` please use `[value]` instead of `[country]`

Finally, I've released a new major [version](https://www.npmjs.com/package/@angular-material-extensions/select-country) of the library `3.0.0`

With this release

<img width="726" alt="Bildschirmfoto 2020-10-23 um 22 36 45" src="https://user-images.githubusercontent.com/20149774/97051865-45719180-1580-11eb-9597-ab8c499ed5e8.png">


https://github.com/angular-material-extensions/select-country/releases/tag/3.0.0


If you love this library please share it with your team and friends and please make sure that your are not missing any 
cool angular library or component within my [angular material extensions](https://github.com/angular-material-extensions)  


thank you all and cheers 🍻

**Comment by ksendart** [comment]
Hey! Got the same behavior with 17.0.0 version. Selector is blank, only flag is displayed after setValue call.

In my standalone component
HTML:
```
<mat-select-country [formControl]="country">
</mat-select-country>
```
TS:
```
@Component({
...
imports: [MatSelectCountryModule, HttpClientModule...],
providers: [
    { provide: MatSelectCountryLangToken, useValue: 'en' },
  ],
})
...

constructor() {
    this.country = new FormControl();
    this.country.setValue({
        "name": "Australia",
        "alpha2Code": "AU",
        "alpha3Code": "AUS",
        "numericCode": "036",
        "callingCode": "+61"
    });
}
```

Result:
<img width="535" alt="selector 2024-05-29" src="https://github.com/angular-material-extensions/select-country/assets/23372522/69bc2377-a0af-4b26-b309-40996002ac24">
