### ISSUE TITLE
SVG images countries are not being copied to the proper location (with a fix)

### ISSUE THREAD

**Issue by kfirufk** [angular-material-extensions/select-country#37]
Hi

I installed this wonderful package using the docs, I need to install it manually because of a bug in schematics that was already reported.

the readme states to configure the following in angular.json

` "output": "src/assets/svg-country-flags/svg"`

with this it creates a src directory in the compiled list directory of the project. 

when changing to

`  "output": "/assets/svg-country-flags/svg"`

it copies the images to the proper location

I use angular CLI 10.1.0 with angular 10.1.0

**Comment by AnthonyNahas** [comment]
This depends on your baseUrl
