### ISSUE TITLE
country name is displayed with - at end

### ISSUE THREAD

**Issue by neosoft-jaykantj** [angular-material-extensions/select-country#38]
If not passing alpha3Code in countries array then - is displayed after country name.
There should be a condition check if no alpha3Code is set in array then even - should not be displayed
Sorry my bad English
[Please go through this page](https://github.com/angular-material-extensions/select-country/blob/513175a059b04ae8de52fb6d6f370b7936681742/projects/angular-material-extensions/select-country/src/lib/mat-select-country.component.html#L15)

**Comment by KingDarBoja** [comment]
This can be solved by just passing the entire word by using `join` on array of strings, something like:

```ts
const countryFinalName = [country?.name, country?.alpha3Code].join('-')]
```

Then use `countryFinalName` at the template.

**Comment by AnthonyNahas** [comment]
@KingDarBoja can u please check ur PR with the latest version of the library pls ?

**Comment by KingDarBoja** [comment]
Alright, let me take a look, as GH doesn't show any conflict with master branch, however a rebase should be done before merging 🚀

**Comment by KingDarBoja** [comment]
![image](https://user-images.githubusercontent.com/30560560/97054303-2eb04800-154a-11eb-8594-74c37f0d7881.png)

Still working as expected, if `alpha3Code` isn't set, it will not display the `-` symbol after country name and viceversa.
