### ISSUE TITLE
Marking the form control as required does not show a * beside the field.

### ISSUE THREAD

**Issue by sankranti2018** [angular-material-extensions/select-country#48]
**Is your feature request related to a problem? Please describe.**
Marking the form control as required does not show a * beside the field.
**Describe the solution you'd like**
When  a material form field is marked as required, the * shows up beside the field. I do not see it when using mat-select-country. Tried on html tag and in the type script file as well...
**Describe alternatives you've considered**

**Additional context**

**Comment by AnthonyNahas** [comment]
this has been fixed in [v3.0.3](https://www.npmjs.com/package/@angular-material-extensions/select-country)

```html
  <mat-select-country appearance="outline"
                            label="Country"
                            [required]="true">
</mat-select-country>
```
