### ISSUE TITLE
console.log() still present in the last version

### ISSUE THREAD

**Issue by christophe-mailfert** [angular-material-extensions/select-country#49]
**Describe the bug**
Some console.log is writen by the module.

lang en
angular-material-extensions-select-country.js:205 running with default
angular-material-extensions-select-country.js:129 writeValue

**To Reproduce**
1. Load module
2 Display field in reactiv form
4. Open console

**Expected behavior**
I think debug log should never appear.

**Desktop (please complete the following information):**
 - Version 3.0.2

**Comment by AnthonyNahas** [comment]
I will move them out in the next release

thank you

**Comment by AnthonyNahas** [comment]
this has been fixed in [v3.0.3](https://www.npmjs.com/package/@angular-material-extensions/select-country)
