### ISSUE TITLE
Flag source in development mode

### ISSUE THREAD

**Issue by e1ad** [angular-material-extensions/select-country#54]
**Describe the bug**
Running development mode (ng serve) i getting the wrong source for the flags :

**To Reproduce**

I follow the steps from 'https://www.npmjs.com/package/@angular-material-extensions/select-country#installation'
to add the 'select-country' to my project.

this step : 

![Capture](https://user-images.githubusercontent.com/13506706/105517472-c35c4a80-5cdf-11eb-90d0-6087df16cb1b.JPG)

is relevant only for production

**Expected behavior**
 i getting the wrong source for the flags

**Screenshots**
![Capture](https://user-images.githubusercontent.com/13506706/105517255-7b3d2800-5cdf-11eb-8eaa-def218e8d97a.JPG)

**Desktop (please complete the following information):**
Windows 10 PC with Chrome Browser

**Additional context**

**Comment by ChristoforosFa** [comment]
i have the same problem.

**Comment by AnthonyNahas** [comment]
what is your baseUrl ?

**Comment by alekw** [comment]
in my tsconfig.json: "baseUrl": "./",

**Comment by e1ad** [comment]
For tsconfig.json "./" .  Or if you are talking about Angular http baseUrl provider I do not  use it.

**Comment by adibenmati** [comment]
same...

**Comment by AnthonyNahas** [comment]
try this 

```json
 {
                "glob": "**/*",
                "input": "./node_modules/svg-country-flags/svg",
                "output": "/assets/svg-country-flags/svg"
 }
`
``

**Comment by e1ad** [comment]
thanks ... works

**Comment by AnthonyNahas** [comment]
you are welcome
