### ISSUE TITLE
Error when trying to install latest version on Angular 10

### ISSUE THREAD

**Issue by MauricioPaez** [angular-material-extensions/select-country#61]
**Describe the bug**
Hi there! I am getting an error when installing the extension. When I install it through npm i @angular-material-extensions/select-country, the version installed is "@angular-material-extensions/select-country": "3.0.4" and this version does not have the callingCode property in the Country interface. When I try to install like npm i @angular-material-extensions/select-country@latest the following error is shown

![image](https://user-images.githubusercontent.com/26752783/112657864-8eff3900-8e9e-11eb-9de9-028c2db59587.png)

When I run ng version I get this:

`Your global Angular CLI version (11.2.6) is greater than your local version (10.0.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".    

Angular CLI: 10.0.4
Node: 14.16.0
OS: win32 x64

Angular: 10.0.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.4
@angular-devkit/build-angular      0.1000.4
@angular-devkit/build-optimizer    0.1000.4
@angular-devkit/build-webpack      0.1000.4
@angular-devkit/core               10.0.4
@angular-devkit/schematics         10.0.4
@angular/cdk                       10.1.0
@angular/cli                       10.0.4
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.1.0
@angular/material-moment-adapter   10.1.0
@ngtools/webpack                   10.0.4
@schematics/angular                11.2.6
@schematics/update                 0.1000.4
rxjs                               6.6.0
typescript                         3.9.7
webpack                            4.43.0`

**To Reproduce**
1. Create/test on an angular project with an angular cli version greater than 9.
2. Install the extension
3. Check the version of the extension installed
4. Try to install using the @latest flag

**Expected behavior**
Install the latest version of the extension in a project that uses Angular 10.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Well, as for additional information I can say that I am running a project that already uses angular material components and that hasn't had any other issues installing other packages so far. Please excuse me if I am being too shallow in providing information,  I am quite new to reporting bugs for this kind of project.

**Comment by MauricioPaez** [comment]
Also, planing on upgrading application to Angular 11, will this be an impediment on using the extension? Cheers and thanks in advance for your help (:

**Comment by nouhouari** [comment]
Same issue for me with angular 10.2.4 version.
![image](https://user-images.githubusercontent.com/15186671/113700882-f83a4400-9709-11eb-9c94-5e76044a08d4.png)

**Comment by nouhouari** [comment]
> Same issue for me with angular 10.2.4 version.
> ![image](https://user-images.githubusercontent.com/15186671/113700882-f83a4400-9709-11eb-9c94-5e76044a08d4.png)

I'm able to install it by forcing the installation.

**Comment by AnthonyNahas** [comment]
The library has peer dependencies to angular material v11, so I thnink to use the lib you should update your dependencies...

**Comment by nouhouari** [comment]
> The library has peer dependencies to angular material v11, so I thnink to use the lib you should update your dependencies...

What if we can't?

**Comment by AnthonyNahas** [comment]
Please use `--force` while installing if you don't have the right peer dependencies!
