### ISSUE TITLE
not working on Angular 11.2.11

### ISSUE THREAD

**Issue by BlueRayNL** [angular-material-extensions/select-country#66]
while running ->ng add @angular-material-extensions/select-country

npm ERR! Found: @angular/cdk@11.2.11
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^11.2.11" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"~11.0.0" from @angular-material-extensions/select-country@4.1.0
npm ERR! node_modules/@angular-material-extensions/select-country

please resolve issue.

**Comment by AnthonyNahas** [comment]
This is because you did not install the angular cdk package ! 

If you are still facing any problem with that, please do not hesitate to reopen this ticket!
