### ISSUE TITLE
Localization for other languages?

### ISSUE THREAD

**Issue by matteobucci** [angular-material-extensions/select-country#7]
I've just found this project and I found it amazing! 
However I'm wondering: is there any support for localization in other languages? Is this something achievable manually or planned?

**Comment by AnthonyNahas** [comment]
I will take this feature into consideration for the next release

**Comment by matteobucci** [comment]
Thank you very much Anthony. I know that I shouldn't ask but, since this is a library I'm willing to use in one of my projects, have you any idea about when it will be implemented?
Furthermore, is there anything that I can do to help you in implementing this feature? I would be very happy to give my contribution.

**Comment by AnthonyNahas** [comment]
@matteobucci I have like over 20 open source projects that I maintain + 2 own productive apps ...
that's why this could be implemented in the next few weeks (maybe earlier)

The idea behind i18n for this library: 

1. First option: via `@Input()` --> 
2. or via angular v9 i18n 

the db should be translated too..

**Comment by EduardoSimon** [comment]
Hi, any way this could be integrated with https://github.com/ngx-translate/core?

**Comment by fuegonju** [comment]
I'm looking forward to be able to use other languages too

**Comment by AnthonyNahas** [comment]
Supporting i18n could be a challenge

**Comment by ACMCMC** [comment]
Are translations for new languages welcome?

**Comment by AnthonyNahas** [comment]
@ACMCMC yes why not

**Comment by Benny739** [comment]
Any plans when you will release the changes with the language support?

**Comment by AnthonyNahas** [comment]
@Benny739 I have more than 15 open source projects to maintain... so please be patient 🍻

**Comment by rodent129** [comment]
Can help to add Chinese translation? Thanks a lot.

**Comment by AnthonyNahas** [comment]
yes you can do it via an appropriate PR

**Comment by Rogermax** [comment]
I made a PR (#80) solving this. This issue is the same as #67. 

I hope it works.

**Comment by jdayssol** [comment]
@Rogermax , thanks for this PR! I hope this will be merged soon, I will need this feature for my project :)
