### ISSUE TITLE
some flags are broken when selecting options 

### ISSUE THREAD

**Issue by sebastiancorrea81** [angular-material-extensions/select-country#84]
when selecting in the select the flag of Uruguay, the flags of Chile, Brazil and Venezuela. They look broken

![imagen](https://user-images.githubusercontent.com/14328989/138883720-16a3871e-988c-46b0-b1fd-b54326a2a76f.png)
![imagen](https://user-images.githubusercontent.com/14328989/138883764-4f85b546-71ac-4e8b-b754-d8263dff8469.png)

**Comment by AnthonyNahas** [comment]
since the flags are from third party lib, I would close this ticket!

Please open an issue in the related repo
