### ISSUE TITLE
Request for Angular v13 Support?

### ISSUE THREAD

**Issue by Solat-Ali** [angular-material-extensions/select-country#86]
Can we please get this repo updated to support latest Angular v13?

**Comment by Solat-Ali** [comment]
@AnthonyNahas Is support for Angular v13 in the near future Anthony? Can you please share a roadmap if possible? Thank you!

**Comment by sasafister** [comment]
I would also like to have support for Angular 13. Any idea when this would be available?

**Comment by prosidney** [comment]
+1

**Comment by NashIlli** [comment]
+1

**Comment by simionrobert** [comment]
+1

**Comment by NashIlli** [comment]
Hello! Any update on this? Thanks!

**Comment by AnthonyNahas** [comment]
[v6](https://www.npmjs.com/package/@angular-material-extensions/select-country) is now live 

angular v13 is now supported

**Comment by Solat-Ali** [comment]
@AnthonyNahas 
Thank you man!!! Will check it out!

**Comment by prosidney** [comment]
You rock man, thanks

**Comment by AnthonyNahas** [comment]
you're welcome bro

**Comment by NashIlli** [comment]
@AnthonyNahas you're awesome! thanks!
