### ISSUE TITLE
Bug - Text not rendered on mat-stepper reactive forms

### ISSUE THREAD

**Issue by simionrobert** [angular-material-extensions/select-country#95]
**Describe the bug**
The label is not shown when using angular material stepper with reactive forms and ngx-translate. It will appear only if the user clicks on it:
```
<mat-select-country label="{{'Tara *'|translate}}" [itemsLoadSize]="10" formControlName="tara">
</mat-select-country>
```

**Screenshots**
![Screenshot 2022-03-12 211509](https://user-images.githubusercontent.com/30863036/158031827-5833693d-4a7f-42bb-acae-f443d4e94797.png)
![Screenshot 2022-03-12 211538](https://user-images.githubusercontent.com/30863036/158031830-88e87401-dd32-4aaa-b173-a01cf083f2cd.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version latest

**Comment by nosTa1337** [comment]
@simionrobert have you solved it?

**Comment by nosTa1337** [comment]
I have the same issue.

It seems like the translation takes place to late. The issue occurs in `<div matformfieldnotchedoutline="" class="mdc-notched-outline ng-tns-c35-12 mdc-notched-outline--no-label ng-star-inserted" ng-reflect-open="false" ng-reflect-label-width="200">`. It adds "no-label.

My solution is to translate it in the ts file and add a listener as well to translate it there, than use the variable in the HTML [label] tag.

````
//  needed as the mat-country-picker has a bug with the translation inline. seems like the translation takes place to late and no-label is used instead.
    this.countryTranslation = this.translateService.instant('CHECKOUT.FORM.COUNTRY');
    
    this.translateService.onLangChange.subscribe(() => {
      this.countryTranslation = this.translateService.instant('CHECKOUT.FORM.COUNTRY');
    })`
```
